---
title: "`r title`"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
      css: ../css/dark.css
---

<div class="dropdown">
  <button class="dropbtn"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#CDD9E5" class="bi bi-list" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
</svg>
</button>

<div class="dropdown-content">
<a href="alfalfa_dark.html">Alfalfa</a>
<a href="almonds_dark.html">Almonds</a>
<a href="cherries_dark.html">Cherries</a>
<a href="citrus_dark.html">Citrus</a>
<a href="corn_dark.html">Corn</a>       
<a href="misc_vegs_&_fruits_dark.html">Misc Vegs & Fruits</a> 
<a href="olives_dark.html">Olives</a>  
<a href="peaches_dark.html">Peaches</a>
<a href="pistachios_dark.html">Pistachios</a>
<a href="plums_dark.html">Plums</a>
<a href="rice_dark.html">Rice</a>
<a href="walnuts_dark.html">Walnuts</a>
<a href="wine_grapes_dark.html">Wine Grapes</a>
</div>
</div>


<button class='btn' onclick="window.location.href='index.html'">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#FFC101" class="bi bi-sun">
      <path d="M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm0 1a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </svg>
</button>


```{r, include=FALSE}
# configure graphs
knitr::opts_chunk$set(comment=NA, echo=FALSE, fig.width=20, fig.height=9, fig.align="center", warning=FALSE)

# set wider print outputs
options(width=500)

# script code
source('../utils/utils.R')
```

```{r}
# plot ndvi
visualize(df, gt, pr, 'NDVI', crop, year, dark=TRUE)
visualize(df_1, gt, pr, 'NDVI', crop, year, dark=TRUE)
visualize(df_2, gt, pr, 'NDVI', crop, year, dark=TRUE)
visualize(df_3, gt, pr, 'NDVI', crop, year, dark=TRUE)
visualize(df_4, gt, pr, 'NDVI', crop, year, dark=TRUE)

# plot eto
visualize(df, gt, pr, 'Eto', crop, year, dark=TRUE)
visualize(df_1, gt, pr, 'Eto', crop, year, dark=TRUE)
visualize(df_2, gt, pr, 'Eto', crop, year, dark=TRUE)
visualize(df_3, gt, pr, 'Eto', crop, year, dark=TRUE)
visualize(df_4, gt, pr, 'Eto', crop, year, dark=TRUE)

# plot kcb
visualize(df, gt, pr, 'Kcb', crop, year, dark=TRUE)
visualize(df_1, gt, pr, 'Kcb', crop, year, dark=TRUE)
visualize(df_2, gt, pr, 'Kcb', crop, year, dark=TRUE)
visualize(df_3, gt, pr, 'Kcb', crop, year, dark=TRUE)
visualize(df_4, gt, pr, 'Kcb', crop, year, dark=TRUE)
```